# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Sat Sep 28 22:29:51 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 670)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tablewidget = QtGui.QTableWidget(self.centralwidget)
        self.tablewidget.setGeometry(QtCore.QRect(10, 0, 451, 581))
        self.tablewidget.setLineWidth(1)
        self.tablewidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablewidget.setRowCount(291)
        self.tablewidget.setObjectName("tablewidget")
        self.tablewidget.setColumnCount(4)
        self.tablewidget.setRowCount(291)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(8, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(9, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(10, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(11, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(12, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(13, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(14, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(15, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(16, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(17, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(18, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(19, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(20, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(21, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(22, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(59, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(70, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget.setItem(71, 3, item)
        self.stopall = QtGui.QPushButton(self.centralwidget)
        self.stopall.setGeometry(QtCore.QRect(310, 590, 98, 27))
        self.stopall.setObjectName("stopall")
        self.resumeall = QtGui.QPushButton(self.centralwidget)
        self.resumeall.setGeometry(QtCore.QRect(200, 590, 98, 27))
        self.resumeall.setObjectName("resumeall")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 538, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "episode", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "size(mb)", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "downladed", None, QtGui.QApplication.UnicodeUTF8))
        self.tablewidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "resume/pause", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tablewidget.isSortingEnabled()
        self.tablewidget.setSortingEnabled(False)
        self.tablewidget.setSortingEnabled(__sortingEnabled)
        self.stopall.setText(QtGui.QApplication.translate("MainWindow", "Stop All", None, QtGui.QApplication.UnicodeUTF8))
        self.resumeall.setText(QtGui.QApplication.translate("MainWindow", "Resume All", None, QtGui.QApplication.UnicodeUTF8))

